apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broken-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: broken-api
    spec:
      containers:
      - name: app
        image: nginx
